# Generated by Django 5.1.7 on 2025-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1500)),
                ('category', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=1000)),
                ('ai_score', models.IntegerField()),
            ],
        ),
    ]
